# Generated by Django 3.0.3 on 2020-12-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClarifyDoubtModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=264)),
                ('subject', models.CharField(max_length=264)),
                ('doubt_pic', models.ImageField(upload_to='pics')),
                ('doubt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DoubtModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=264)),
                ('subject', models.CharField(max_length=264)),
                ('language', models.CharField(max_length=264)),
                ('doubt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LIVEClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=263)),
                ('subject', models.CharField(max_length=264)),
                ('date', models.CharField(max_length=264)),
                ('time', models.CharField(max_length=264)),
                ('query', models.TextField()),
            ],
        ),
    ]
