# Generated by Django 3.0.3 on 2020-11-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoubtModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=264)),
                ('subject', models.CharField(max_length=264)),
                ('language', models.CharField(max_length=264)),
                ('doubt', models.TextField()),
            ],
        ),
    ]
