# Generated by Django 3.0.3 on 2020-12-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0002_clarifydoubtmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clarifydoubtmodel',
            name='doubt_pic',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
