# Generated by Django 3.0.3 on 2020-12-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0003_auto_20201201_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clarifydoubtmodel',
            name='doubt_pic',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
